apiVersion: v1
kind: Pod
metadata:
  name: custom-app
  labels:
    app: custom-app
spec:
  containers:
  - name: python-app
    image: 663839140840.dkr.ecr.ap-south-1.amazonaws.com/python-web-app:v5
    ports:
    - containerPort: 80
  imagePullSecrets:
    - name: ecr-secret
