apiVersion: v1
kind: Service
metadata:
  name: custom-app-node-port-service
spec:
  selector:
    app: custom-app-dep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234
  type: NodePort
